import Head from 'next/head'
import '@/styles/Home.module.css'
import { useTranslation } from 'next-i18next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import Banner from '@/components/Banner/Banner';

export default function Home() {

  const { t } = useTranslation();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='vh-100'>
        <h1 className='text-center pt-4'>{t('homePage.bannerHome.btn_slider_one')} Home</h1>
          <p className='text-center'>{t('components.read_more')}</p>
          <p>{t('locale')}</p>
          <Banner />
      </main>
    </>
  )
}

export const getStaticProps = async ({ locale }) => {
  
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common'])),
    },
  };
};

